# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.increment_counter200_response import IncrementCounter200Response

class TestIncrementCounter200Response(unittest.TestCase):
    """IncrementCounter200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncrementCounter200Response:
        """Test IncrementCounter200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncrementCounter200Response`
        """
        model = IncrementCounter200Response()
        if include_optional:
            return IncrementCounter200Response(
                new_counter_value = 1.337,
                message = '',
                success = True,
                error = monday_code.models.error.error()
            )
        else:
            return IncrementCounter200Response(
                new_counter_value = 1.337,
                message = '',
                success = True,
                error = monday_code.models.error.error(),
        )
        """

    def testIncrementCounter200Response(self):
        """Test IncrementCounter200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
