# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.download_file_response import DownloadFileResponse

class TestDownloadFileResponse(unittest.TestCase):
    """DownloadFileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DownloadFileResponse:
        """Test DownloadFileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DownloadFileResponse`
        """
        model = DownloadFileResponse()
        if include_optional:
            return DownloadFileResponse(
                success = True,
                error = '',
                content = 'YQ==',
                content_type = ''
            )
        else:
            return DownloadFileResponse(
                success = True,
        )
        """

    def testDownloadFileResponse(self):
        """Test DownloadFileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
