# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import AsyncMock, patch, MagicMock

from monday_code.api.logs_api import LogsApi
from monday_code.models.write_log_request_body import WriteLogRequestBody
from monday_code.models.log_methods import LogMethods


class TestLogsApi(unittest.IsolatedAsyncioTestCase):
    """LogsApi comprehensive tests"""

    async def asyncSetUp(self) -> None:
        """Set up test fixtures before each test method."""
        with patch('monday_code.api_client.ApiClient'):
            self.api = LogsApi()

        # Mock the API client with proper async/sync method setup
        self.mock_client = MagicMock()

        # Async methods should use AsyncMock
        self.mock_client.call_api = AsyncMock()

        # Sync methods should use regular MagicMock
        self.mock_client.param_serialize = MagicMock()
        self.mock_client.select_header_accept = MagicMock()
        self.mock_client.select_header_content_type = MagicMock()
        self.mock_client.response_deserialize = MagicMock()

        self.api.api_client = self.mock_client

    async def asyncTearDown(self) -> None:
        """Clean up after each test method."""
        pass

    async def test_write_log_success(self) -> None:
        """Test successful log writing"""
        # Arrange
        log_body = WriteLogRequestBody(
            message="Test log message",
            method=LogMethods.INFO
        )

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "log_123"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        # Test logging
        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.write_log(log_body)

            # Assert
            self.assertEqual(result, {"success": True, "id": "log_123"})
            self.mock_client.call_api.assert_called_once()

            # Verify logging - find our specific log message
            sdk_logs = [msg for msg in log.output if "Writing log entry" in msg]
            self.assertEqual(len(sdk_logs), 1)
            self.assertIn("📝 Writing log entry", sdk_logs[0])

    async def test_write_log_error_level(self) -> None:
        """Test writing error level log"""
        # Arrange
        log_body = WriteLogRequestBody(
            message="Critical error occurred",
            method=LogMethods.ERROR
        )

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "error_log_456"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.write_log(log_body)

            # Assert
            self.assertEqual(result, {"success": True, "id": "error_log_456"})
            # Check list length before accessing elements (Monday best practice)
            if len(log.output) > 0:
                sdk_logs = [msg for msg in log.output if "Writing log entry" in msg]
                self.assertGreater(len(sdk_logs), 0)
                self.assertIn("📝 Writing log entry", sdk_logs[0])

    async def test_write_log_with_metadata(self) -> None:
        """Test writing log with additional metadata"""
        # Arrange
        log_body = WriteLogRequestBody(
            message="Debug information",
            method=LogMethods.DEBUG
        )

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "debug_log_789"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.write_log(log_body)

            # Assert
            self.assertEqual(result, {"success": True, "id": "debug_log_789"})
            # Check list length before accessing elements (Monday best practice)
            if len(log.output) > 0:
                sdk_logs = [msg for msg in log.output if "Writing log entry" in msg]
                self.assertGreater(len(sdk_logs), 0)
                self.assertIn("📝 Writing log entry", sdk_logs[0])

    async def test_write_log_with_custom_headers(self) -> None:
        """Test writing log with custom headers"""
        # Arrange
        log_body = WriteLogRequestBody(
            message="Warning message",
            method=LogMethods.WARN
        )
        custom_headers = {"X-Custom-Header": "custom_value"}

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "warn_log_999"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO'):
            # Act
            result = await self.api.write_log(
                log_body,
                _headers=custom_headers
            )

            # Assert
            self.assertEqual(result, {"success": True, "id": "warn_log_999"})

    async def test_write_log_with_timeout(self) -> None:
        """Test writing log with custom timeout"""
        # Arrange
        log_body = WriteLogRequestBody(
            message="Timeout test message",
            method=LogMethods.INFO
        )
        custom_timeout = 15.0

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "timeout_log_111"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO'):
            # Act
            result = await self.api.write_log(
                log_body,
                _request_timeout=custom_timeout
            )

            # Assert
            self.assertEqual(result, {"success": True, "id": "timeout_log_111"})
            # Verify timeout was passed to call_api
            call_args = self.mock_client.call_api.call_args
            self.assertEqual(call_args.kwargs['_request_timeout'], custom_timeout)

    async def test_write_log_large_message(self) -> None:
        """Test writing log with large message"""
        # Arrange
        large_message = "X" * 1000  # 1KB message
        log_body = WriteLogRequestBody(
            message=large_message,
            method=LogMethods.INFO
        )

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/logs", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = {"success": True, "id": "large_log_222"}
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.write_log(log_body)

            # Assert
            self.assertEqual(result, {"success": True, "id": "large_log_222"})
            # Check list length before accessing elements (Monday best practice)
            if len(log.output) > 0:
                sdk_logs = [msg for msg in log.output if "Writing log entry" in msg]
                self.assertGreater(len(sdk_logs), 0)
                self.assertIn("📝 Writing log entry", sdk_logs[0])

    async def test_api_client_initialization(self) -> None:
        """Test that API client is properly initialized"""
        # Test that our mock setup worked
        self.assertIsNotNone(self.api.api_client)
        self.assertEqual(self.api.api_client, self.mock_client)


if __name__ == '__main__':
    unittest.main()
