# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.period import Period

class TestPeriod(unittest.TestCase):
    """Period unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriod(self):
        """Test Period"""
        # inst = Period()

if __name__ == '__main__':
    unittest.main()
