# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.environment_variables_api import EnvironmentVariablesApi


class TestEnvironmentVariablesApi(unittest.TestCase):
    """EnvironmentVariablesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnvironmentVariablesApi()

    def tearDown(self) -> None:
        pass

    def test_get_environment_variable(self) -> None:
        """Test case for get_environment_variable

        """
        pass

    def test_get_environment_variable_keys(self) -> None:
        """Test case for get_environment_variable_keys

        """
        pass


if __name__ == '__main__':
    unittest.main()
