# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.list_files_response import ListFilesResponse

class TestListFilesResponse(unittest.TestCase):
    """ListFilesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFilesResponse:
        """Test ListFilesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFilesResponse`
        """
        model = ListFilesResponse()
        if include_optional:
            return ListFilesResponse(
                success = True,
                error = '',
                files = [
                    monday_code.models.file_info.FileInfo(
                        metadata = {
                            'key' : ''
                            }, 
                        etag = '', 
                        last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        content_type = '', 
                        size = 1.337, 
                        name = '', )
                    ],
                next_page_token = ''
            )
        else:
            return ListFilesResponse(
                success = True,
        )
        """

    def testListFilesResponse(self):
        """Test ListFilesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
