# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import AsyncMock, patch, MagicMock

from monday_code.api.queue_api import QueueApi
from monday_code.models.publish_message_params import PublishMessageParams
from monday_code.models.validate_secret_params import ValidateSecretParams


class TestQueueApi(unittest.IsolatedAsyncioTestCase):
    """QueueApi comprehensive tests"""

    async def asyncSetUp(self) -> None:
        """Set up test fixtures before each test method."""
        with patch('monday_code.api_client.ApiClient'):
            self.api = QueueApi()

        # Mock the API client with proper async/sync method setup
        self.mock_client = MagicMock()

        # Async methods should use AsyncMock
        self.mock_client.call_api = AsyncMock()

        # Sync methods should use regular MagicMock
        self.mock_client.param_serialize = MagicMock()
        self.mock_client.select_header_accept = MagicMock()
        self.mock_client.select_header_content_type = MagicMock()
        self.mock_client.response_deserialize = MagicMock()

        self.api.api_client = self.mock_client

    async def asyncTearDown(self) -> None:
        """Clean up after each test method."""
        pass

    async def test_publish_message_success(self) -> None:
        """Test successful message publishing"""
        # Arrange
        message_params = PublishMessageParams(
            message="{\"event\": \"user_created\", \"user_id\": \"123\"}"
        )
        expected_response = {
            "message_id": "msg_456",
            "status": "published",
            "timestamp": "2024-01-15T10:30:00Z"
        }

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        # Test logging
        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.publish_message(message_params)

            # Assert
            self.assertEqual(result, expected_response)
            self.mock_client.call_api.assert_called_once()

            # Verify logging
            self.assertEqual(len(log.output), 1)
            self.assertIn("📬 Publishing message to queue", log.output[0])

    async def test_publish_message_high_priority(self) -> None:
        """Test publishing high priority message"""
        # Arrange
        message_params = PublishMessageParams(
            message="{\"alert\": \"system_down\", \"severity\": \"critical\"}"
        )
        expected_response = {
            "message_id": "msg_urgent_789",
            "status": "published",
            "priority_processed": True
        }

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.publish_message(message_params)

            # Assert
            self.assertEqual(result, expected_response)
            self.assertIn("📬 Publishing message to queue", log.output[0])

    async def test_publish_message_with_metadata(self) -> None:
        """Test publishing message with additional metadata"""
        # Arrange
        message_params = PublishMessageParams(
            message="{\"type\": \"email\", \"recipient\": \"user@example.com\"}"
        )
        expected_response = {"message_id": "msg_meta_999", "status": "queued"}

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO'):
            # Act
            result = await self.api.publish_message(message_params)

            # Assert
            self.assertEqual(result, expected_response)

    async def test_validate_secret_success(self) -> None:
        """Test successful secret validation"""
        # Arrange
        secret_params = ValidateSecretParams(
            secret="correct_secret_value_123"
        )
        expected_response = {
            "valid": True,
            "secret_name": "webhook_secret",
            "validated_at": "2024-01-15T10:30:00Z"
        }

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        # Test logging
        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.validate_secret(secret_params)

            # Assert
            self.assertEqual(result, expected_response)
            self.assertTrue(result["valid"])
            self.mock_client.call_api.assert_called_once()

            # Verify logging (should not expose secret value)
            self.assertEqual(len(log.output), 1)
            self.assertIn("📬 Validating secret in queue", log.output[0])
            self.assertNotIn("correct_secret_value_123", log.output[0])

    async def test_validate_secret_invalid(self) -> None:
        """Test secret validation with invalid secret"""
        # Arrange
        secret_params = ValidateSecretParams(
            secret="wrong_value"
        )
        expected_response = {
            "valid": False,
            "secret_name": "api_key",
            "error": "Invalid secret value"
        }

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO') as log:
            # Act
            result = await self.api.validate_secret(secret_params)

            # Assert
            self.assertEqual(result, expected_response)
            self.assertFalse(result["valid"])
            self.assertIn("📬 Validating secret in queue", log.output[0])

    async def test_validate_secret_with_additional_context(self) -> None:
        """Test secret validation with additional context"""
        # Arrange
        secret_params = ValidateSecretParams(
            secret="token_xyz_789"
        )
        expected_response = {
            "valid": True,
            "secret_name": "integration_token",
            "context_validated": True
        }

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO'):
            # Act
            result = await self.api.validate_secret(secret_params)

            # Assert
            self.assertEqual(result, expected_response)
            self.assertTrue(result["valid"])

    async def test_publish_message_with_timeout(self) -> None:
        """Test publishing message with custom timeout"""
        # Arrange
        message_params = PublishMessageParams(
            message="{\"batch_id\": \"batch_123\", \"items_count\": 1000}"
        )
        custom_timeout = 60.0
        expected_response = {"message_id": "msg_batch_111", "status": "queued"}

        # Mock the serialization and API call properly
        mock_param = ("POST", "/api/queue", {}, None, [])
        self.mock_client.param_serialize.return_value = mock_param
        self.mock_client.select_header_accept.return_value = "application/json"
        self.mock_client.select_header_content_type.return_value = "application/json"

        # Mock successful API response
        mock_response_data = MagicMock()
        mock_response_data.read = AsyncMock()  # response.read() is async
        self.mock_client.call_api.return_value = mock_response_data

        # Mock response deserialize to return object with .data
        mock_deserialized = MagicMock()
        mock_deserialized.data = expected_response
        self.mock_client.response_deserialize.return_value = mock_deserialized

        with self.assertLogs(level='INFO'):
            # Act
            result = await self.api.publish_message(
                message_params,
                _request_timeout=custom_timeout
            )

            # Assert
            self.assertEqual(result, expected_response)
            # Verify timeout was passed to call_api
            call_args = self.mock_client.call_api.call_args
            self.assertEqual(call_args.kwargs['_request_timeout'], custom_timeout)

    async def test_api_client_initialization(self) -> None:
        """Test that API client is properly initialized"""
        # Test that our mock setup worked
        self.assertIsNotNone(self.api.api_client)
        self.assertEqual(self.api.api_client, self.mock_client)


if __name__ == '__main__':
    unittest.main()
