# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.secure_storage_api import SecureStorageApi


class TestSecureStorageApi(unittest.IsolatedAsyncioTestCase):
    """SecureStorageApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SecureStorageApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_delete_secure_storage(self) -> None:
        """Test case for delete_secure_storage

        """
        pass

    async def test_get_secure_storage(self) -> None:
        """Test case for get_secure_storage

        """
        pass

    async def test_put_secure_storage(self) -> None:
        """Test case for put_secure_storage

        """
        pass


if __name__ == '__main__':
    unittest.main()
