# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.write_log_request_body_error import WriteLogRequestBodyError

class TestWriteLogRequestBodyError(unittest.TestCase):
    """WriteLogRequestBodyError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WriteLogRequestBodyError:
        """Test WriteLogRequestBodyError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WriteLogRequestBodyError`
        """
        model = WriteLogRequestBodyError()
        if include_optional:
            return WriteLogRequestBodyError(
            )
        else:
            return WriteLogRequestBodyError(
        )
        """

    def testWriteLogRequestBodyError(self):
        """Test WriteLogRequestBodyError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
