# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.get_file_info_response import GetFileInfoResponse

class TestGetFileInfoResponse(unittest.TestCase):
    """GetFileInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFileInfoResponse:
        """Test GetFileInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFileInfoResponse`
        """
        model = GetFileInfoResponse()
        if include_optional:
            return GetFileInfoResponse(
                success = True,
                error = '',
                file_info = monday_code.models.file_info.FileInfo(
                    metadata = {
                        'key' : ''
                        }, 
                    etag = '', 
                    last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    content_type = '', 
                    size = 1.337, 
                    name = '', )
            )
        else:
            return GetFileInfoResponse(
                success = True,
        )
        """

    def testGetFileInfoResponse(self):
        """Test GetFileInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
