# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.object_storage_api import ObjectStorageApi


class TestObjectStorageApi(unittest.TestCase):
    """ObjectStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectStorageApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        """
        pass

    def test_download_file(self) -> None:
        """Test case for download_file

        """
        pass

    def test_get_file_info(self) -> None:
        """Test case for get_file_info

        """
        pass

    def test_list_files(self) -> None:
        """Test case for list_files

        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
