# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.secret_api import SecretApi


class TestSecretApi(unittest.TestCase):
    """SecretApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecretApi()

    def tearDown(self) -> None:
        pass

    def test_get_secret(self) -> None:
        """Test case for get_secret

        """
        pass


if __name__ == '__main__':
    unittest.main()
