# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.storage_api import StorageApi


class TestStorageApi(unittest.IsolatedAsyncioTestCase):
    """StorageApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = StorageApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_delete_by_key_from_storage(self) -> None:
        """Test case for delete_by_key_from_storage

        """
        pass

    async def test_get_by_key_from_storage(self) -> None:
        """Test case for get_by_key_from_storage

        """
        pass

    async def test_increment_counter(self) -> None:
        """Test case for increment_counter

        """
        pass

    async def test_search_record(self) -> None:
        """Test case for search_record

        """
        pass

    async def test_upsert_by_key_from_storage(self) -> None:
        """Test case for upsert_by_key_from_storage

        """
        pass


if __name__ == '__main__':
    unittest.main()
