# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.logs_api import LogsApi


class TestLogsApi(unittest.IsolatedAsyncioTestCase):
    """LogsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LogsApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_write_log(self) -> None:
        """Test case for write_log

        """
        pass


if __name__ == '__main__':
    unittest.main()
