# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.models.increment_counter200_response_any_of import IncrementCounter200ResponseAnyOf

class TestIncrementCounter200ResponseAnyOf(unittest.TestCase):
    """IncrementCounter200ResponseAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncrementCounter200ResponseAnyOf:
        """Test IncrementCounter200ResponseAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncrementCounter200ResponseAnyOf`
        """
        model = IncrementCounter200ResponseAnyOf()
        if include_optional:
            return IncrementCounter200ResponseAnyOf(
                new_counter_value = None,
                message = None,
                success = True,
                error = ''
            )
        else:
            return IncrementCounter200ResponseAnyOf(
                success = True,
                error = '',
        )
        """

    def testIncrementCounter200ResponseAnyOf(self):
        """Test IncrementCounter200ResponseAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
