# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_code.api.queue_api import QueueApi


class TestQueueApi(unittest.IsolatedAsyncioTestCase):
    """QueueApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = QueueApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_publish_message(self) -> None:
        """Test case for publish_message

        """
        pass

    async def test_validate_secret(self) -> None:
        """Test case for validate_secret

        """
        pass


if __name__ == '__main__':
    unittest.main()
