# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monday_sdk.api.storage_api import StorageApi


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageApi()

    def tearDown(self) -> None:
        pass

    def test_delete_storage(self) -> None:
        """Test case for delete_storage

        """
        pass

    def test_get_storage(self) -> None:
        """Test case for get_storage

        """
        pass

    def test_put_storage(self) -> None:
        """Test case for put_storage

        """
        pass

    def test_storage_increment_counter(self) -> None:
        """Test case for storage_increment_counter

        """
        pass


if __name__ == '__main__':
    unittest.main()
