# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Period(str, Enum):
    """
    Period
    """

    """
    allowed enum values
    """
    DAILY = 'DAILY'
    MONTHLY = 'MONTHLY'
    YEARLY = 'YEARLY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Period from a JSON string"""
        return cls(json.loads(json_str))


