# coding: utf-8

"""
    mcode-sdk-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from monday_code.models.increment_counter200_response_any_of import IncrementCounter200ResponseAnyOf
from monday_code.models.increment_counter200_response_any_of1 import IncrementCounter200ResponseAnyOf1
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

INCREMENTCOUNTER200RESPONSE_ANY_OF_SCHEMAS = ["IncrementCounter200ResponseAnyOf", "IncrementCounter200ResponseAnyOf1"]

class IncrementCounter200Response(BaseModel):
    """
    IncrementCounter200Response
    """

    # data type: IncrementCounter200ResponseAnyOf
    anyof_schema_1_validator: Optional[IncrementCounter200ResponseAnyOf] = None
    # data type: IncrementCounter200ResponseAnyOf1
    anyof_schema_2_validator: Optional[IncrementCounter200ResponseAnyOf1] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[IncrementCounter200ResponseAnyOf, IncrementCounter200ResponseAnyOf1]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "IncrementCounter200ResponseAnyOf", "IncrementCounter200ResponseAnyOf1" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = IncrementCounter200Response.model_construct()
        error_messages = []
        # validate data type: IncrementCounter200ResponseAnyOf
        if not isinstance(v, IncrementCounter200ResponseAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IncrementCounter200ResponseAnyOf`")
        else:
            return v

        # validate data type: IncrementCounter200ResponseAnyOf1
        if not isinstance(v, IncrementCounter200ResponseAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IncrementCounter200ResponseAnyOf1`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in IncrementCounter200Response with anyOf schemas: IncrementCounter200ResponseAnyOf, IncrementCounter200ResponseAnyOf1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[IncrementCounter200ResponseAnyOf] = None
        try:
            instance.actual_instance = IncrementCounter200ResponseAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[IncrementCounter200ResponseAnyOf1] = None
        try:
            instance.actual_instance = IncrementCounter200ResponseAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into IncrementCounter200Response with anyOf schemas: IncrementCounter200ResponseAnyOf, IncrementCounter200ResponseAnyOf1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], IncrementCounter200ResponseAnyOf, IncrementCounter200ResponseAnyOf1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


